import { Audiowide, Geist, Geist_Mono } from "next/font/google";
import { ReactNode } from "react";

import RootProvider from "./provider";
import Header from "@/components/layouts/Header";

import type { Metadata } from "next";

import "@/globals.css";

/*
 * Fonts
 */

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

const audiowide = Audiowide({
  subsets: ["latin"],
  weight: "400",
});

/*
 * Metadata
 */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*
 * Local Types
 */

type RootLayoutProps = {
  children: ReactNode;
};

/*
 * Component
 */

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} grid h-dvh grid-rows-[auto_1fr] bg-gray-200 antialiased`}
      >
        <RootProvider>
          <Header className={audiowide.className} />
          <main>{children}</main>
        </RootProvider>
      </body>
    </html>
  );
}
